apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solana-ledger-pvc
  namespace: solana-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi # Adjust size as needed
