apiVersion: v1
kind: Service
metadata:
  name: solana-validator-service
  namespace: solana-test
spec:
  type: NodePort
  ports:
    - port: 8899
      targetPort: 8899
      protocol: TCP
  selector:
    app: solana-validator
